feat: add possibility to send cards
julb/alertmanager-gchat-integration pull request #4
Opened 2021-03-12 13:13 UTC by antoinerabany

Hi,

I just wanted to add possibility to send cards for nicer display.

https://developers.google.com/hangouts/chat/reference/message-formats/cards

I'll add an example of a working card template as soon I have a working one. 

Thanks again.

2021-03-14 11:12 UTC, julb commented
Hello @antoinerabany, that's a very interesting contribution, thanks !
I've done some remarks in your PR.
The main feedback is (I suppose): if `use_cards=true`, the template `render` will output `json` but as a `string`. In such case, we need to add a `json.loads(...)` to transform the `text_alert` value to a `dict`, otherwise the call to Google Chat will fail.

2021-03-14 11:16 UTC, julb requested changes

2021-03-14 11:16 UTC, julb commented on alertmanager_gchat_integration/app.py
> +                message_type: text_alert
if `CONFIG['app']['notification'].get('use_cards')` is true, `text_alert` needs to be converted to a `dict` using `json.loads(text_alert)`.

2021-03-14 11:16 UTC, julb commented on alertmanager_gchat_integration/app.py
>          text_alert = J2_TEMPLATE_ENGINE.render(render_payload)
Consider maybe to rename the `text_alert` variable to `rendered_alert` to avoid confusion.

2021-03-17 11:40 UTC, antoinerabany commented
Hello,

Thanks for your feedback, I implemented your changes.

2021-03-18 15:34 UTC, julb commented
Thanks a lot @antoinerabany 👍
I will look at it by tomorrow and gets it released if everything is OK.

2021-03-19 10:05 UTC, julb approved these changes

2021-03-19 10:05 UTC, merged

2021-03-19 12:03 UTC, julb commented
Project is released, as well as the associated [Helm Charts](https://github.com/julb/helm-charts/tree/main/julb/alertmanager-gchat-integration).
Thanks for your contribution 👍